# Generated by Django 5.0.6 on 2024-05-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnomalyDetectionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol_type", models.CharField(max_length=50)),
                ("service", models.CharField(max_length=50)),
                ("flag", models.CharField(max_length=50)),
                ("src_bytes", models.IntegerField()),
                ("dst_bytes", models.IntegerField()),
                ("count", models.IntegerField()),
                ("same_srv_rate", models.FloatField()),
                ("diff_srv_rate", models.FloatField()),
                ("dst_host_srv_count", models.IntegerField()),
                ("dst_host_same_srv_rate", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
